
export const locations = [
  "Adilabad",
  "Adoni",
  "Agra",
  "Ahmedabad",
  "Ahmednagar",
  "Aizawl",
  "Ajmer",
  "Akola",
  "Alappuzha",
  "Aligarh",
  "Alirajpur",
  "Allahabad",
  "Amalapuram",
  "Amravati",
  "Amritsar",
  "Amroha",
  "Anakapalle",
  "Anand",
  "Anantapur",
  "Anantnag",
  "Anjaw",
  "Anuppur",
  "Araria",
  "Aravalli",
  "Ariyalur",
  "Arwal",
  "Asansol",
  "Ashoknagar",
  "Auraiya",
  "Aurangabad",
  "Azamgarh",
  "Badepally",
  "Badvel",
  "Bagalkot",
  "Bageshwar",
  "Baghpat",
  "Bahraich",
  "Baksa",
  "Balaghat",
  "Balangir",
  "Baleswar",
  "Ballia",
  "Balrampur",
  "Banas Kantha",
  "Banda",
  "Bandipora",
  "Bangalore Rural",
  "Bangalore Urban",
  "Banka",
  "Bankura",
  "Banswara",
  "Barabanki",
  "Baramulla",
  "Baran",
  "Bardhaman",
  "Bareilly",
  "Bargarh",
  "Barmer",
  "Barnala",
  "Barpeta",
  "Barwani",
  "Bastar",
  "Basti",
  "Bathinda",
  "Beed",
  "Begusarai",
  "Belgaum",
  "Bellampalli",
  "Bellary",
  "Bengaluru",
  "Betul",
  "Bhadradri Kothagudem",
  "Bhadrak",
  "Bhagalpur",
  "Bhandara",
  "Bharatpur",
  "Bharuch",
  "Bhavnagar",
  "Bhilai",
  "Bhilwara",
  "Bhimavaram",
  "Bhind",
  "Bhiwani",
  "Bhojpur",
  "Bhopal",
  "Bidar",
  "Bijapur",
  "Bijnor",
  "Bikaner",
  "Bilaspur",
  "Birbhum",
  "Bishnupur",
  "Bobbili",
  "Bodhan",
  "Bokaro",
  "Bongaigaon",
  "Boudh",
  "Budaun",
  "Bulandshahr",
  "Buldhana",
  "Bundi",
  "Burhanpur",
  "Buxar",
  "Cachar",
  "Central Delhi",
  "Chamarajanagar",
  "Chamba",
  "Chamoli",
  "Champawat",
  "Champhai",
  "Chandauli",
  "Chandel",
  "Chandigarh",
  "Chandrapur",
  "Changlang",
  "Chatra",
  "Chennai",
  "Chhatarpur",
  "Chhindwara",
  "Chikkaballapur",
  "Chikkamagaluru",
  "Chilakaluripet",
  "Chirala",
  "Chitradurga",
  "Chitrakoot",
  "Chittoor",
  "Chittorgarh",
  "Churachandpur",
  "Coimbatore",
  "Cooch Behar",
  "Cuddalore",
  "Cuttack",
  "Dadra and Nagar Haveli",
  "Dahod",
  "Dakshin Dinajpur",
  "Dakshina Kannada",
  "Daman",
  "Damoh",
  "Dantewada",
  "Darbhanga",
  "Darjeeling",
  "Darrang",
  "Datia",
  "Dausa",
  "Davanagere",
  "Dehradun",
  "Deoghar",
  "Deoria",
  "Dewas",
  "Dhalai",
  "Dhamtari",
  "Dhanbad",
  "Dhar",
  "Dharmapuri",
  "Dharmavaram",
  "Dharwad",
  "Dhemaji",
  "Dhenkanal",
  "Dholpur",
  "Dhubri",
  "Dhule",
  "Dibang Valley",
  "Dibrugarh",
  "Dima Hasao",
  "Dimapur",
  "Dindigul",
  "Dindori",
  "Diu",
  "Doda",
  "Dumka",
  "Dungarpur",
  "Durg",
  "East Champaran",
  "East Delhi",
  "East Garo Hills",
  "East Godavari",
  "East Kameng",
  "East Khasi Hills",
  "East Siang",
  "East Sikkim",
  "East Singhbhum",
  "Eluru",
  "Ernakulam",
  "Erode",
  "Etah",
  "Etawah",
  "Faizabad",
  "Faridabad",
  "Faridkot",
  "Farrukhabad",
  "Fatehabad",
  "Fatehgarh Sahib",
  "Fatehpur",
  "Fazilka",
  "Firozabad",
  "Firozpur",
  "Gadag",
  "Gadchiroli",
  "Gadiguntla",
  "Gadwal",
  "Gajapati",
  "Ganderbal",
  "Gandhinagar",
  "Ganganagar",
  "Ganjam",
  "Garhwa",
  "Gariaband",
  "Gautam Buddh Nagar",
  "Gaya",
  "Ghaziabad",
  "Ghazipur",
  "Giridih",
  "Goalpara",
  "Godda",
  "Golaghat",
  "Gonda",
  "Gondia",
  "Gopalganj",
  "Gorakhpur",
  "Gudivada",
  "Gudur",
  "Gumla",
  "Guna",
  "Guntur",
  "Gurdaspur",
  "Gurgaon",
  "Gwalior",
  "Hailakandi",
  "Hamirpur",
  "Hanumangarh",
  "Harda",
  "Hardoi",
  "Haridwar",
  "Hassan",
  "Hathras",
  "Haveri",
  "Hazaribagh",
  "Hindupur",
  "Hingoli",
  "Hisar",
  "Hojai",
  "Hooghly",
  "Hoshangabad",
  "Hoshiarpur",
  "Howrah",
  "Hyderabad",
  "Idukki",
  "Imphal East",
  "Imphal West",
  "Indore",
  "Jabalpur",
  "Jagatsinghpur",
  "Jagtial",
  "Jaipur",
  "Jaisalmer",
  "Jajpur",
  "Jalandhar",
  "Jalaun",
  "Jalgaon",
  "Jalna",
  "Jalore",
  "Jalpaiguri",
  "Jammu",
  "Jamnagar",
  "Jamtara",
  "Jamui",
  "Jangaon",
  "Janjgir-Champa",
  "Jashpur",
  "Jaunpur",
  "Jhabua",
  "Jhajjar",
  "Jhalawar",
  "Jhansi",
  "Jharsuguda",
  "Jhunjhunu",
  "Jind",
  "Jodhpur",
  "Jorhat",
  "Junagadh",
  "Kadapa",
  "Kadi",
  "Kagaznagar",
  "Kaimur",
  "Kaithal",
  "Kakinada",
  "Kalahandi",
  "Kalaburagi",
  "Kamareddy",
  "Kamrup",
  "Kamrup Metropolitan",
  "Kanchipuram",
  "Kandhamal",
  "Kangra",
  "Kanker",
  "Kannauj",
  "Kannur",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kanyakumari",
  "Kapurthala",
  "Karaikal",
  "Karauli",
  "Karbi Anglong",
  "Kargil",
  "Karimganj",
  "Karimnagar",
  "Karnal",
  "Karur",
  "Kasaragod",
  "Kathua",
  "Katihar",
  "Katni",
  "Kaushambi",
  "Kavali",
  "Kendrapara",
  "Kendujhar",
  "Khagaria",
  "Khammam",
  "Khandwa",
  "Khargone",
  "Kheda",
  "Khordha",
  "Khowai",
  "Khunti",
  "Kinnaur",
  "Kiphire",
  "Kisan Ganj",
  "Kishtwar",
  "Kodad",
  "Kodagu",
  "Koderma",
  "Kohima",
  "Kolar",
  "Kolasib",
  "Kolhapur",
  "Kolkata",
  "Kollam",
  "Koppal",
  "Koraput",
  "Korba",
  "Koriya",
  "Kota",
  "Kothagudem",
  "Kottayam",
  "Kovvur",
  "Kozhikode",
  "Krishna",
  "Krishnagiri",
  "Kulgam",
  "Kullu",
  "Kupwara",
  "Kurnool",
  "Kurukshetra",
  "Kurung Kumey",
  "Kushinagar",
  "Kutch",
  "Lakhimpur",
  "Lakhimpur Kheri",
  "Lakhisarai",
  "Lalitpur",
  "Latehar",
  "Latur",
  "Lawngtlai",
  "Leh",
  "Lohardaga",
  "Lohit",
  "Longleng",
  "Lower Dibang Valley",
  "Lower Subansiri",
  "Lucknow",
  "Ludhiana",
  "Lunglei",
  "Madhepura",
  "Madhubani",
  "Madurai",
  "Mahabubabad",
  "Mahabubnagar",
  "Maharajganj",
  "Mahasamund",
  "Mahe",
  "Mahendragarh",
  "Mahisagar",
  "Mahoba",
  "Mainpuri",
  "Malappuram",
  "Malda",
  "Malkajgiri",
  "Malkangiri",
  "Mamit",
  "Mancherial",
  "Mandi",
  "Mandla",
  "Mandsaur",
  "Mandya",
  "Mansa",
  "Markapur",
  "Mathura",
  "Mau",
  "Mayurbhanj",
  "Medak",
  "Medchal",
  "Meerut",
  "Mehsana",
  "Miryalaguda",
  "Mirzapur",
  "Moga",
  "Mohali",
  "Mokokchung",
  "Mon",
  "Moradabad",
  "Morbi",
  "Morena",
  "Mumbai City",
  "Mumbai Suburban",
  "Munger",
  "Murshidabad",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Mysore",
  "Nabarangpur",
  "Nadia",
  "Nagaon",
  "Nagapattinam",
  "Nagarkurnool",
  "Nagaur",
  "Nagpur",
  "Nainital",
  "Nalgonda",
  "Nalbari",
  "Namakkal",
  "Nanded",
  "Nandurbar",
  "Narayanpur",
  "Narmada",
  "Narsapur",
  "Narsinghpur",
  "Narsipatnam",
  "Narwana",
  "Nashik",
  "Navsari",
  "Nawada",
  "Nawanshahr",
  "Nayagarh",
  "Neemuch",
  "Nellore",
  "New Delhi",
  "Nilgiris",
  "Nirmal",
  "Nizamabad",
  "Noida",
  "North 24 Parganas",
  "North Delhi",
  "North East Delhi",
  "North Garo Hills",
  "North Goa",
  "North Sikkim",
  "North Tripura",
  "North West Delhi",
  "Nuapada",
  "Nuh",
  "Nuzvid",
  "Ongole",
  "Osmanabad",
  "Pakur",
  "Palakkad",
  "Palamu",
  "Palani",
  "Palanpur",
  "Palghar",
  "Pali",
  "Palwal",
  "Palwancha",
  "Panchkula",
  "Panchmahal",
  "Panipat",
  "Panna",
  "Papum Pare",
  "Paramakudi",
  "Parbhani",
  "Parvathipuram",
  "Paschim Medinipur",
  "Patan",
  "Pathanamthitta",
  "Pathankot",
  "Patiala",
  "Patna",
  "Pauri Garhwal",
  "Peddapalli",
  "Perambalur",
  "Peren",
  "Phek",
  "Pilibhit",
  "Pithoragarh",
  "Pondicherry",
  "Poonch",
  "Porbandar",
  "Prakasam",
  "Pratapgarh",
  "Proddatur",
  "Pudukkottai",
  "Pulwama",
  "Pune",
  "Purba Medinipur",
  "Puri",
  "Purnia",
  "Purulia",
  "Rae Bareli",
  "Raichur",
  "Raigad",
  "Raigarh",
  "Raipur",
  "Raisen",
  "Rajahmundry",
  "Rajanna Sircilla",
  "Rajgarh",
  "Rajkot",
  "Rajnandgaon",
  "Rajouri",
  "Rajsamand",
  "Ramanagara",
  "Ramanathapuram",
  "Ramban",
  "Ramgarh",
  "Rampur",
  "Ranchi",
  "Rangareddy",
  "Ratlam",
  "Ratnagiri",
  "Rayachoti",
  "Rayagada",
  "Reasi",
  "Rewa",
  "Rewari",
  "Ri Bhoi",
  "Rohtak",
  "Rohtas",
  "Rudraprayag",
  "Rupnagar",
  "Sabarkantha",
  "Sagar",
  "Saharanpur",
  "Saharsa",
  "Sahibganj",
  "Saiha",
  "Salem",
  "Samastipur",
  "Samba",
  "Sambalpur",
  "Sambhal",
  "Sangareddy",
  "Sangli",
  "Sangrur",
  "Sant Kabir Nagar",
  "Sant Ravidas Nagar",
  "Saran",
  "Satara",
  "Satna",
  "Sawai Madhopur",
  "Sehore",
  "Senapati",
  "Seoni",
  "Sepahijala",
  "Seraikela Kharsawan",
  "Serchhip",
  "Shahdol",
  "Shahjahanpur",
  "Shajapur",
  "Shamli",
  "Sheikhpura",
  "Sheohar",
  "Sheopur",
  "Shimla",
  "Shimoga",
  "Shivpuri",
  "Shopian",
  "Shravasti",
  "Siddharthnagar",
  "Siddipet",
  "Sidhi",
  "Sikar",
  "Simdega",
  "Sindhudurg",
  "Singrauli",
  "Sirmaur",
  "Sirohi",
  "Sirsa",
  "Sitamarhi",
  "Sitapur",
  "Sivaganga",
  "Siwan",
  "Solan",
  "Solapur",
  "Sonbhadra",
  "Sonipat",
  "Sonitpur",
  "South 24 Parganas",
  "South Andaman",
  "South Delhi",
  "South East Delhi",
  "South Garo Hills",
  "South Goa",
  "South Sikkim",
  "South Tripura",
  "South West Delhi",
  "South West Garo Hills",
  "South West Khasi Hills",
  "Sri Ganganagar",
  "Sri Potti Sriramulu Nellore",
  "Srikakulam",
  "Srikalahasti",
  "Srinagar",
  "Subarnapur",
  "Sukma",
  "Sultanpur",
  "Sundargarh",
  "Supaul",
  "Surajpur",
  "Surat",
  "Surendranagar",
  "Suryapet",
  "Tadepalligudem",
  "Tadipatri",
  "Tamenglong",
  "Tandur",
  "Tanuku",
  "Tapi",
  "Tarn Taran",
  "Tawang",
  "Tehri Garhwal",
  "Tenali",
  "Thane",
  "Thanjavur",
  "The Dangs",
  "Theni",
  "Thiruvananthapuram",
  "Thoothukudi",
  "Thoubal",
  "Thrissur",
  "Tikamgarh",
  "Tinsukia",
  "Tirap",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupati",
  "Tiruppur",
  "Tiruvallur",
  "Tiruvannamalai",
  "Tiruvarur",
  "Tonk",
  "Tuensang",
  "Tumkur",
  "Udaipur",
  "Udalguri",
  "Udham Singh Nagar",
  "Udupi",
  "Ujjain",
  "Ukhrul",
  "Umaria",
  "Una",
  "Unakoti",
  "Unnao",
  "Upper Siang",
  "Upper Subansiri",
  "Uttar Dinajpur",
  "Uttara Kannada",
  "Uttarkashi",
  "Vadodara",
  "Vaishali",
  "Valsad",
  "Varanasi",
  "Vellore",
  "Venkatagiri",
  "Vidisha",
  "Vijayawada",
  "Vikarabad",
  "Viluppuram",
  "Vinukonda",
  "Virudhunagar",
  "Visakhapatnam",
  "Vizianagaram",
  "Wanaparthy",
  "Warangal Rural",
  "Warangal Urban",
  "Wardha",
  "Washim",
  "Wayanad",
  "West Champaran",
  "West Delhi",
  "West Garo Hills",
  "West Godavari",
  "West Kameng",
  "West Khasi Hills",
  "West Siang",
  "West Sikkim",
  "West Singhbhum",
  "West Tripura",
  "Wokha",
  "Yadadri Bhuvanagiri",
  "Yadgir",
  "Yamunanagar",
  "Yanam",
  "Yavatmal",
  "YSR Kadapa",
  "Zunheboto"
];
